### ISSUE TITLE
[BUG] <title>MiniCPM-V-2的vLLM推理不能使用

### ISSUE THREAD

**Issue by y-x-x123** [OpenBMB/MiniCPM-V#361] opened 2024-07-23 08:43 UTC
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

MiniCPM-V-2的vLLM推理不能使用了 
MiniCPM-Llama3-V 2.5是可以的

### 期望行为 | Expected Behavior

-

### 复现方法 | Steps To Reproduce

-

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

-

**Comment by renjingneng** [comment] 2024-07-24 03:43
我是 MiniCPM-Llama3-V 2.5 都不能用
  报错：AttributeError: 'list' object has no attribute 'to'

**Comment by y-x-x123** [comment] 2024-07-24 09:12
> 我是 MiniCPM-Llama3-V 2.5 都不能用 报错：AttributeError: 'list' object has no attribute 'to'

MiniCPM-Llama3-V 2.5 我这边可以正常推理  但是MiniCPM-V-2的更没了

**Comment by renjingneng** [comment] 2024-07-24 10:28
> > 我是 MiniCPM-Llama3-V 2.5 都不能用 报错：AttributeError: 'list' object has no attribute 'to'
> 
> MiniCPM-Llama3-V 2.5 我这边可以正常推理 但是MiniCPM-V-2的更没了

你是怎么操作的，也是按照文档这样吗？
```
git clone https://github.com/OpenBMB/vllm.git
cd vllm
git checkout minicpmv
pip install -e .
pip install timm=0.9.10
python examples/minicpmv_example.py 
```

**Comment by HwwwwwwwH** [comment] 2024-07-25 06:48
2.5 Should be run with no error now. As for 2, the official code has not been support yet. 
I create a new repo of `MiniCPM-V-2` on HF for vllm. You can use it temporarily: https://huggingface.co/HwwwH/MiniCPM-V-2.
Maybe this code will be merged into official HF repo after some necessary testing.

**Comment by y-x-x123** [comment] 2024-07-25 07:24
> > > 我是 MiniCPM-Llama3-V 2.5 都不能用 报错：AttributeError: 'list' object has no attribute 'to'
> > 
> > 
> > MiniCPM-Llama3-V 2.5 我这边可以正常推理 但是MiniCPM-V-2的更没了
> 
> 你是怎么操作的，也是按照文档这样吗？
> 
> ```
> git clone https://github.com/OpenBMB/vllm.git
> cd vllm
> git checkout minicpmv
> pip install -e .
> pip install timm=0.9.10
> python examples/minicpmv_example.py 
> ```

是的啊 我就是这样操作的

**Comment by y-x-x123** [comment] 2024-07-25 07:27
> 2.5 should be run with no error now. As for 2, the official code has not supported `vllm` yet. I create a new repo of `MiniCPM-V-2` on HF for vllm. You can use it temporarily: https://huggingface.co/HwwwH/MiniCPM-V-2. Maybe this code will be merged into official HF repo after some necessary testing.

Thank you for your reply.

**Comment by xiaohuihui52309** [comment] 2024-07-25 12:18
#

> > 2.5 should be run with no error now. As for 2, the official code has not supported `vllm` yet. I create a new repo of `MiniCPM-V-2` on HF for vllm. You can use it temporarily: https://huggingface.co/HwwwH/MiniCPM-V-2. Maybe this code will be merged into official HF repo after some necessary testing.
> 
> Thank you for your reply.

推理成功了吗

**Comment by renjingneng** [comment] 2024-07-26 08:50
> > > 2.5 should be run with no error now. As for 2, the official code has not supported `vllm` yet. I create a new repo of `MiniCPM-V-2` on HF for vllm. You can use it temporarily: https://huggingface.co/HwwwH/MiniCPM-V-2. Maybe this code will be merged into official HF repo after some necessary testing.
> > 
> > 
> > Thank you for your reply.
> 
> 推理成功了吗

我试了 没成功  
报错：
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 380, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 547, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 238, in __init__
    self.tokenizer = self._init_tokenizer()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 495, in _init_tokenizer
    return get_tokenizer_group(self.parallel_config.tokenizer_pool_config,
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer_group/__init__.py", line 34, in get_tokenizer_group
    return tokenizer_cls.from_config(tokenizer_pool_config, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 31, in from_config
    return cls(**init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 24, in __init__
    self.tokenizer = get_tokenizer(self.tokenizer_id, **tokenizer_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer.py", line 95, in get_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 881, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2291, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2525, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/HwwwH_MiniCPM-V-2/tokenization_minicpmv.py", line 8, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 171, in __init__
    self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 198, in get_spm_processor
    tokenizer.Load(self.vocab_file)
  File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

**Comment by iceflame89** [comment] 2024-07-26 11:54
@renjingneng   To use MiniCPM-V 2.5 with vllm,  2.5 model code should be updated to the same latest version as 
 [openbmb/MiniCPM-Llama3-V-2_5](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5) on Hugging Face.

**Comment by renjingneng** [comment] 2024-07-29 10:38
> @renjingneng To use MiniCPM-V 2.5 with vllm, 2.5 model code should be updated to the same latest version as [openbmb/MiniCPM-Llama3-V-2_5](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5) on Hugging Face.


ok so only MiniCPM-Llama3-V 2.5 be used for  vllm

**Comment by HwwwwwwwH** [comment] 2024-07-29 12:48
> > @renjingneng To use MiniCPM-V 2.5 with vllm, 2.5 model code should be updated to the same latest version as [openbmb/MiniCPM-Llama3-V-2_5](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5) on Hugging Face.
> 
> ok so only MiniCPM-Llama3-V 2.5 be used for vllm

!! It should've be run successfully with V2. I check the reason of your traceback. I guess this may caused by the lfs tokenizer files. Check if these files are downloaded correctly. 
![image](https://github.com/user-attachments/assets/de9f2db0-5758-4923-af66-d629107152a9)

**Comment by HwwwwwwwH** [comment] 2024-07-29 12:48
> > > @renjingneng To use MiniCPM-V 2.5 with vllm, 2.5 model code should be updated to the same latest version as [openbmb/MiniCPM-Llama3-V-2_5](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5) on Hugging Face.
> > 
> > 
> > ok so only MiniCPM-Llama3-V 2.5 be used for vllm
> 
> !! It should've be run successfully with V2. I've checked the reason of your traceback. I guess this may caused by the lfs tokenizer files. Check if these files are downloaded correctly. ![image](https://private-user-images.githubusercontent.com/52458637/353066325-de9f2db0-5758-4923-af66-d629107152a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTc2MTksIm5iZiI6MTcyMjI1NzMxOSwicGF0aCI6Ii81MjQ1ODYzNy8zNTMwNjYzMjUtZGU5ZjJkYjAtNTc1OC00OTIzLWFmNjYtZDYyOTEwNzE1MmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEyNDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZmRjZWU2N2JiMDkxYWI3NzE4NGFiMDE4OTgwN2I2N2MwZTg4M2MxZDJkNTI4ODc5M2ZkYjI0ZjVhMjc5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zSRjY5j9FC02se4V8r9RUCK06wc2Im1VGnMh5KLHMs0)

**Closed** 2024-07-31 08:31 UTC

**Comment by heylamourding** [comment] 2024-09-04 07:29
hi @HwwwwwwwH  does openbmb/MiniCPM-V-2 work now? 

i tried to send messages to HwwwH/MiniCPM-V-2 but model cannot read image. May I know how to solve it? 

```
json_data = {
    'model': 'HwwwH/MiniCPM-V-2',
    'messages': [
        {
            'role': 'user',
            'content': [
                {
                    'type': 'text',
                    'text': "describe image in details",
                },
                {
                    'type': 'image_url',
                    'image_url': {
                        'url': f'data:image/png;base64,{img_b64}'
                    },
                },
            ],
        },
    ] 
} 
```

**Comment by Uooga** [comment] 2024-12-16 12:29
> 我是 MiniCPM-Llama3-V 2.5 都不能用 报错：AttributeError: 'list' object has no attribute 'to'

我进行infer也是相同的错误，请问你是通过更新了hf上最新的代码解决的吗？
